site_name: DirectMultiStep Docs
repo_url: https://github.com/batistagroup/DirectMultiStep
repo_name: batistagroup/DirectMultiStep
copyright: CC-BY 4.0 &copy; 2025 Batista Group
theme:
  name: material
  features:
    - content.code.copy
    - navigation.footer
  palette:
      # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
- stylesheets/extra.css

plugins:
- search
- mkdocstrings
- material-plausible

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
      
  - admonition
  - pymdownx.details

extra:
  analytics:
    provider: plausible
    domain: dms.batistalab.com

    # : If using custom domain proxy or self-hosting Plausible,
    # : uncomment and specify script path here:
    src: "https://analytics.batistalab.com/js/script.js"

    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: good
          note: >-
            Thanks for your feedback!

        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: bad
          note: >-
            Thanks for your feedback!