site_name: DirectMultiStep Docs
repo_url: https://github.com/batistagroup/DirectMultiStep
repo_name: batistagroup/DirectMultiStep
copyright: CC-BY 4.0 &copy; 2025 Batista Group
theme:
  name: material
  features:
    - content.code.copy

extra_css:
- stylesheets/extra.css

plugins:
- search
- mkdocstrings

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
