name: Linting

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/uv
          ~/.uv
          .venv
        key: ${{ runner.os }}-uv-${{ hashFiles('pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-uv-

    - name: Create and activate virtual environment
      run: |
        uv venv
        echo "$PWD/.venv/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: uv sync

    - name: Run ruff (linter)
      run: ruff check

    - name: Run ruff (formatter)
      run: ruff format --check

    - name: Run mypy
      run: mypy .