name: Code Quality
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.11"
    - run: pip install --upgrade pip
    - run: pip install ruff mypy black pytest
    - run: black .
    - run: ruff format
    - run: ruff check --fix
    - run: mypy --strict . --exclude=tests
    - run: pytest -v